In [2]:
import utils as ut

In [3]:
data = ut.res_load('cora_res', 'HP')
tab, mean = ut.split_methods(data, '_mean')
mean

metrics,Hits@20,Hits@50,Hits@100,ROCAUC,AP,pretrain_time
"baseline,enc:gcn_ncn,pred:mlp_mean",64.09$\pm$1.28,76.75$\pm$1.06,85.74$\pm$0.95,95.08$\pm$0.27,95.38$\pm$0.27,nan$\pm$nan
"grace,enc:gcn_ncn,pred:mlp,random_mean",59.33$\pm$4.21,75.5$\pm$2.2,84.04$\pm$0.76,93.63$\pm$0.27,94.13$\pm$0.31,5.07$\pm$0.01
"grace,enc:gcn_ncn,pred:mlp,deg_mean",51.17$\pm$4.35,70.56$\pm$4.82,84.31$\pm$2.6,94.72$\pm$0.71,94.33$\pm$0.78,18.24$\pm$0.08
"grace,enc:gcn_ncn,pred:mlp,evc_mean",59.91$\pm$4.98,76.9$\pm$2.96,87.1$\pm$1.76,95.07$\pm$0.53,95.11$\pm$0.45,31.96$\pm$0.1
"grace,enc:gcn_ncn,pred:mlp,pr_mean",55.89$\pm$3.79,73.9$\pm$1.94,84.63$\pm$1.54,94.56$\pm$0.6,94.47$\pm$0.61,16.27$\pm$0.03
"bgrl,enc:gcn_ncn,pred:mlp,random_mean",57.29$\pm$3.63,73.65$\pm$2.11,84.33$\pm$1.29,93.93$\pm$0.4,94.19$\pm$0.35,28.19$\pm$0.16
"bgrl,enc:gcn_ncn,pred:mlp,deg_mean",50.55$\pm$3.23,65.72$\pm$2.68,76.12$\pm$1.52,91.06$\pm$0.49,91.79$\pm$0.53,11.74$\pm$0.01
"bgrl,enc:gcn_ncn,pred:mlp,evc_mean",63.76$\pm$3.93,76.8$\pm$2.12,84.69$\pm$1.0,93.79$\pm$0.63,94.59$\pm$0.44,26.95$\pm$0.35
"bgrl,enc:gcn_ncn,pred:mlp,pr_mean",50.34$\pm$4.63,71.58$\pm$3.19,84.5$\pm$0.94,93.96$\pm$0.38,93.9$\pm$0.5,27.09$\pm$0.45
"lbgrl,enc:gcn_ncn,pred:mlp,random_mean",51.59$\pm$3.26,70.86$\pm$2.62,83.29$\pm$1.55,93.27$\pm$0.54,93.48$\pm$0.46,29.93$\pm$0.42
"lbgrl,enc:gcn_ncn,pred:mlp,deg_mean",53.88$\pm$7.45,72.17$\pm$5.34,83.19$\pm$3.41,94.14$\pm$1.04,94.22$\pm$1.19,18.17$\pm$0.44
"lbgrl,enc:gcn_ncn,pred:mlp,evc_mean",49.86$\pm$5.27,69.06$\pm$4.46,81.7$\pm$1.8,93.3$\pm$0.58,93.26$\pm$0.67,24.53$\pm$0.06
"lbgrl,enc:gcn_ncn,pred:mlp,pr_mean",44.32$\pm$6.89,62.33$\pm$8.03,76.57$\pm$7.23,91.48$\pm$2.28,91.69$\pm$2.45,19.5$\pm$0.13
"lgrace,enc:gcn_ncn,pred:mlp,random_mean",62.86$\pm$3.2,75.71$\pm$1.81,83.07$\pm$1.32,93.02$\pm$0.56,94.0$\pm$0.43,26.63$\pm$0.42
"lgrace,enc:gcn_ncn,pred:mlp,deg_mean",50.3$\pm$7.4,68.17$\pm$8.33,79.36$\pm$7.14,91.64$\pm$2.43,92.43$\pm$2.39,66.31$\pm$0.2
"lgrace,enc:gcn_ncn,pred:mlp,evc_mean",56.67$\pm$5.09,73.86$\pm$2.26,84.8$\pm$1.96,94.62$\pm$0.46,94.59$\pm$0.5,83.36$\pm$4.02
"lgrace,enc:gcn_ncn,pred:mlp,pr_mean",60.1$\pm$4.09,76.92$\pm$2.91,86.93$\pm$1.34,95.45$\pm$0.38,95.36$\pm$0.42,49.87$\pm$2.9

In [4]:
data = ut.res_load('citeseer_res', 'HP')
tab, mean = ut.split_methods(data, '_mean')
mean

metrics,Hits@20,Hits@50,Hits@100,ROCAUC,AP,pretrain_time
"baseline,enc:gcn_ncn,pred:mlp_mean",63.32$\pm$4.11,76.51$\pm$2.41,85.66$\pm$2.07,94.83$\pm$0.98,95.07$\pm$0.86,nan$\pm$nan
"grace,enc:gcn_ncn,pred:mlp,random_mean",62.86$\pm$4.24,77.75$\pm$2.62,89.56$\pm$1.55,95.74$\pm$0.44,95.54$\pm$0.56,10.0$\pm$0.02
"grace,enc:gcn_ncn,pred:mlp,deg_mean",68.93$\pm$2.45,82.6$\pm$2.02,90.22$\pm$0.98,95.89$\pm$0.42,95.97$\pm$0.46,5.14$\pm$0.0
"grace,enc:gcn_ncn,pred:mlp,evc_mean",72.62$\pm$4.76,86.05$\pm$2.19,92.66$\pm$1.28,96.77$\pm$0.41,96.77$\pm$0.5,21.11$\pm$0.02
"grace,enc:gcn_ncn,pred:mlp,pr_mean",71.12$\pm$3.65,83.3$\pm$2.52,90.3$\pm$1.03,96.08$\pm$0.4,96.28$\pm$0.46,2.78$\pm$0.0
"bgrl,enc:gcn_ncn,pred:mlp,random_mean",62.93$\pm$5.01,79.07$\pm$2.29,87.99$\pm$2.26,93.76$\pm$0.79,94.4$\pm$0.86,11.97$\pm$0.02
"bgrl,enc:gcn_ncn,pred:mlp,deg_mean",67.03$\pm$19.66,78.45$\pm$18.67,85.66$\pm$17.82,93.28$\pm$9.37,93.83$\pm$8.24,6.91$\pm$0.12
"bgrl,enc:gcn_ncn,pred:mlp,evc_mean",69.91$\pm$3.63,81.43$\pm$2.57,88.69$\pm$1.59,95.64$\pm$0.43,96.01$\pm$0.46,4.29$\pm$0.01
"bgrl,enc:gcn_ncn,pred:mlp,pr_mean",53.65$\pm$20.55,67.82$\pm$22.47,78.52$\pm$21.32,90.23$\pm$11.07,90.65$\pm$10.01,39.75$\pm$0.23
"lbgrl,enc:gcn_ncn,pred:mlp,random_mean",41.25$\pm$7.65,53.51$\pm$8.8,64.02$\pm$9.23,84.06$\pm$4.29,86.21$\pm$3.73,4.82$\pm$0.04
"lbgrl,enc:gcn_ncn,pred:mlp,deg_mean",55.85$\pm$4.65,71.2$\pm$4.21,82.62$\pm$3.37,93.91$\pm$0.92,93.95$\pm$0.92,19.06$\pm$0.41
"lbgrl,enc:gcn_ncn,pred:mlp,evc_mean",57.24$\pm$5.84,71.41$\pm$4.12,82.05$\pm$2.38,93.52$\pm$0.74,93.85$\pm$0.81,9.01$\pm$0.29
"lbgrl,enc:gcn_ncn,pred:mlp,pr_mean",62.75$\pm$12.2,73.56$\pm$10.67,81.8$\pm$10.84,92.83$\pm$4.8,93.53$\pm$4.29,37.84$\pm$0.29
"lgrace,enc:gcn_ncn,pred:mlp,random_mean",55.67$\pm$14.62,72.12$\pm$15.21,82.41$\pm$15.21,92.95$\pm$6.99,93.01$\pm$6.45,13.02$\pm$6.51
"lgrace,enc:gcn_ncn,pred:mlp,deg_mean",54.43$\pm$7.36,65.98$\pm$8.27,78.0$\pm$7.32,90.79$\pm$2.95,91.73$\pm$2.47,62.29$\pm$0.38
"lgrace,enc:gcn_ncn,pred:mlp,evc_mean",70.81$\pm$4.07,82.96$\pm$1.76,90.26$\pm$1.52,96.12$\pm$0.45,96.35$\pm$0.46,35.9$\pm$3.03
"lgrace,enc:gcn_ncn,pred:mlp,pr_mean",71.63$\pm$12.56,80.62$\pm$12.67,87.66$\pm$11.02,94.78$\pm$4.77,95.39$\pm$4.19,9.51$\pm$0.71

In [5]:
data = ut.res_load('pubmed_res', 'HP')
tab, mean = ut.split_methods(data, '_mean')
mean

metrics,Hits@20,Hits@50,Hits@100,ROCAUC,AP,pretrain_time
"baseline,enc:gcn_ncn,pred:mlp_mean",51.24$\pm$4.38,70.04$\pm$3.06,81.38$\pm$1.66,98.78$\pm$0.05,98.71$\pm$0.07,nan$\pm$nan
"grace,enc:gcn_ncn,pred:mlp,random_mean",48.93$\pm$3.27,64.67$\pm$1.45,75.06$\pm$1.22,97.35$\pm$0.24,97.65$\pm$0.17,519.13$\pm$0.16
"grace,enc:gcn_ncn,pred:mlp,deg_mean",44.43$\pm$5.15,62.93$\pm$3.55,75.36$\pm$1.67,98.37$\pm$0.09,98.29$\pm$0.11,85.07$\pm$0.14
"grace,enc:gcn_ncn,pred:mlp,evc_mean",34.69$\pm$3.43,59.41$\pm$2.73,75.85$\pm$2.05,97.97$\pm$0.09,97.93$\pm$0.14,528.5$\pm$0.29
"grace,enc:gcn_ncn,pred:mlp,pr_mean",52.32$\pm$3.08,69.53$\pm$3.35,79.88$\pm$1.66,98.65$\pm$0.06,98.61$\pm$0.09,416.01$\pm$0.24
"bgrl,enc:gcn_ncn,pred:mlp,random_mean",31.17$\pm$5.56,54.66$\pm$3.83,72.81$\pm$2.49,98.07$\pm$0.08,97.96$\pm$0.16,46.44$\pm$0.04
"bgrl,enc:gcn_ncn,pred:mlp,deg_mean",42.91$\pm$4.44,62.68$\pm$2.96,75.35$\pm$1.69,98.36$\pm$0.07,98.28$\pm$0.1,29.39$\pm$0.11
"bgrl,enc:gcn_ncn,pred:mlp,evc_mean",52.05$\pm$3.24,68.67$\pm$2.18,78.04$\pm$1.06,97.12$\pm$0.14,97.6$\pm$0.1,75.25$\pm$0.16
"bgrl,enc:gcn_ncn,pred:mlp,pr_mean",32.16$\pm$3.53,55.05$\pm$2.62,69.59$\pm$1.96,98.06$\pm$0.07,97.88$\pm$0.11,81.35$\pm$0.12

In [6]:
data = ut.res_load('cora_res', 'HP_SBM')
tab, mean = ut.split_methods(data, '_mean')
mean

metrics,Hits@20,Hits@50,Hits@100,ROCAUC,AP,pretrain_time
leiden_prob_pred_mean,37.82$\pm$4.84,53.17$\pm$1.36,59.06$\pm$1.43,77.76$\pm$0.64,82.49$\pm$0.73,nan$\pm$nan
"grace,enc:gcn_ncn,pred:mlp,sbm+random_mean",49.21$\pm$2.84,69.49$\pm$3.82,82.4$\pm$2.53,93.23$\pm$0.66,93.27$\pm$0.67,372.44$\pm$11.94
"grace,enc:gcn_ncn,pred:mlp,sbm_fast+random_mean",53.42$\pm$4.43,66.59$\pm$4.87,77.28$\pm$2.99,91.74$\pm$1.07,92.48$\pm$0.97,4.52$\pm$0.01
"grace,enc:gcn_ncn,pred:mlp,sbm_fast2_mean",52.46$\pm$4.12,69.9$\pm$1.71,82.0$\pm$1.22,93.42$\pm$0.54,93.5$\pm$0.56,26.32$\pm$0.1
louvain_prob_pred_mean,37.82$\pm$4.84,53.17$\pm$1.36,59.06$\pm$1.43,77.76$\pm$0.64,82.49$\pm$0.73,nan$\pm$nan
"bgrl,enc:gcn_ncn,pred:mlp,sbm+random_mean",31.33$\pm$8.88,44.52$\pm$11.04,55.93$\pm$11.29,82.26$\pm$5.75,83.63$\pm$5.47,126.67$\pm$4.19
"bgrl,enc:gcn_ncn,pred:mlp,sbm_fast+random_mean",55.88$\pm$1.8,64.3$\pm$1.55,72.11$\pm$1.25,87.97$\pm$0.63,90.5$\pm$0.45,24.0$\pm$0.16
"bgrl,enc:gcn_ncn,pred:mlp,sbm_fast2_mean",45.33$\pm$7.47,65.74$\pm$5.4,80.79$\pm$3.67,93.16$\pm$0.87,92.79$\pm$1.1,11.81$\pm$0.02